name: 'Daily Zen Quotes'

on:
  schedule:
    - cron: '0 12 * * 1-5'
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch zen quote
        run: |
          curl -s "https://zenquotes.io/api/random" | jq -r '.[0] | "**\"\(.q)\"**\n\n— _\(.a)_"' > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "moatorres"
          git config --global user.email "moatorres@users.noreply.github.com"
          git add README.md
          git commit -m "chore(ci): updated zen quote"
          git push
