name: 'Daily Wisdom Quotes'

on:
  schedule:
    - cron: '0 12 * * 1-5'
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch wisdom quote
        run: |
          curl -s "https://zenquotes.io/api/random" | jq -r '.[0] | "**\"\(.q)\"**\n\n— _\(.a)_"' > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore(repo): update wisdom quote" || echo "No changes to commit"
          git push
